### ISSUE TITLE
xds_to_zarr is too strict about chunking when writing data variables to zarr datasets

### ISSUE THREAD

**Issue by landmanbester** [ratt-ru/dask-ms#171] opened 2021-11-25 10:01 UTC
* dask-ms version: 0.2.6
* Python version: 3.7.10
* Operating System: ubuntu 18.04

### Description

I keep trying to append or update data to an existing dataset and then getting the zarr chunks don't match dask chunks error thrown [here](https://github.com/ska-sa/dask-ms/blob/55c987e5f00c24a82c16363f681a966e45590e06/daskms/experimental/zarr/__init__.py#L94). I understand why all variables in the dataset need to have the same chunking per coordinate but xds_to_zarr falls over unnecessarily when trying to write data to the dataset. For example, this script
```
import dask
import dask.array as da
import xarray
from daskms.experimental.zarr import xds_from_zarr, xds_to_zarr

D = xarray.Dataset({'uvw': (('row', 'three'), da.zeros((100, 3), chunks=(10, -1))),
                    'weight': (('row', 'chan'), da.zeros((100, 8), chunks=(10,2)))})
writes = xds_to_zarr([D], 'test.zarr', columns='ALL')
dask.compute(writes)
# load in with different chunking
ds = xds_from_zarr('test.zarr/', chunks={'row': 20, 'chan': 2, 'three': 3})[0]
# rechunk weight to match chunking on disk
weight = ds.weight.data.rechunk({0: 10})
ds = ds.assign(**{'weight': (('row', 'chan'), weight)})
writes = xds_to_zarr([ds], 'test.zarr', columns=('weight'))
```  
falls over with 
```
Traceback (most recent call last):
  File "scratch.py", line 15, in <module>
    writes = xds_to_zarr([ds], 'test.zarr', columns=('weight'))
  File "/home/landman/venvs/pfb/lib/python3.7/site-packages/daskms/experimental/zarr/__init__.py", line 233, in xds_to_zarr
    group = prepare_zarr_group(di, ds, store, table)
  File "/home/landman/venvs/pfb/lib/python3.7/site-packages/daskms/experimental/zarr/__init__.py", line 123, in prepare_zarr_group
    schema_chunks = schema.chunks
  File "/home/landman/venvs/pfb/lib/python3.7/site-packages/daskms/dataset_schema.py", line 162, in chunks
    raise ValueError(f"Inconsistent chunks {dim_chunks}"
ValueError: Inconsistent chunks {(10, 10, 10, 10, 10, 10, 10, 10, 10, 10), (20, 20, 20, 20, 20)}for dimension row
```
This does not happen if you open the dataset with ```columns='weight'``` so it must be complaining about uvw but I am not writing uvw so I don't understand why it should fall over. You can get around this by rechunking and also writing out uvw but that incurs unnecessary writes. Why does xds_to_zarr have to check the chunking of data variables that are not being written?

**Comment by sjperkins** [comment] 2021-11-25 11:27
>> Why does xds_to_zarr have to check the chunking of data variables that are not being written?

Thanks for the nice reproducer. The error is getting thrown because there are two arrays with inconsistent chunking for the `row` dimension on the single dataset: `uvw` has chunks of `20` and `weight` has chunks of  `10`.  This mirrors xarray's behaviour

```python
>>> import xarray as xr
>>> import dask.array as da

>>> ds = xr.Dataset({
    "a": (("row", "chan"), da.zeros((100, 16), (10, 4))),
    "b": (("row",), da.zeros(100, chunks=20))})


>>> ds.chunks()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-3a43202e1c7b> in <module>
----> 1 ds.chunks

~/venv/dask-ms/lib/python3.8/site-packages/xarray/core/dataset.py in chunks(self)
   2097                 for dim, c in zip(v.dims, v.chunks):
   2098                     if dim in chunks and c != chunks[dim]:
-> 2099                         raise ValueError(
   2100                             f"Object has inconsistent chunks along dimension {dim}. "
   2101                             "This can be fixed by calling unify_chunks()."

ValueError: Object has inconsistent chunks along dimension row. This can be fixed by calling unify_chunks().
```

In the case of your script, you can call

```python
ds = xds_from_zarr('test.zarr/', chunks={'row': 20, 'chan': 2, 'three': 3})[0]
# rechunk all dataset arrays to match the chunking on disk
ds = ds.chunk({"row": 10})
writes = xds_to_zarr([ds], 'test.zarr', columns=('weight'))
```

Does this solve your problem?

**Comment by JSKenyon** [comment] 2021-11-25 11:35
Isn't the problem that it is complaining about a field which isn't being written? Why do a consistency check on something which doesn't need to be consistent? #118 is similar.

**Comment by landmanbester** [comment] 2021-11-25 11:51
Yeah, that was just a toy reproducer. I don't want to rechunk all the data because there may be a reason for the other variables (uvw in this case) to be chunked up the way they are. I am getting around this currently by opening a separate dataset just for writing. That allows me to read data in with chunks that are say selected for efficient gridding and then I can use the other ds object to write out data using a different chunking scheme. Not sure if that may have unintended consequences though and it means the column I need to write (weight in this case) has to exist in the dataset to begin with. Surely there must be a way to add a new data variable to the .zarr store if it's chunks match those on disk?

**Comment by sjperkins** [comment] 2021-11-25 12:04
> Isn't the problem that it is complaining about a field which isn't being written?

No, its saying that the chunking for the same dimension on different dataset arrays is inconsistent.

```python
Traceback (most recent call last):
  File "scratch.py", line 15, in <module>
    writes = xds_to_zarr([ds], 'test.zarr', columns=('weight'))
  File "/home/landman/venvs/pfb/lib/python3.7/site-packages/daskms/experimental/zarr/__init__.py", line 233, in xds_to_zarr
    group = prepare_zarr_group(di, ds, store, table)
  File "/home/landman/venvs/pfb/lib/python3.7/site-packages/daskms/experimental/zarr/__init__.py", line 123, in prepare_zarr_group
    schema_chunks = schema.chunks
  File "/home/landman/venvs/pfb/lib/python3.7/site-packages/daskms/dataset_schema.py", line 162, in chunks
    raise ValueError(f"Inconsistent chunks {dim_chunks}"
ValueError: Inconsistent chunks {(10, 10, 10, 10, 10, 10, 10, 10, 10, 10), (20, 20, 20, 20, 20)}for dimension row
```

> Why do a consistency check on something which doesn't need to be consistent? #118 is similar.

1. A schema for the zarr hierarchy and file chunking is derived from the supplied datasets
2. This would need to change to either craft new datasets with only the desired columns. This could be tricky given that there is metadata and coordinates that would also need to munged.

Interestingly, xarray will swallow inconsistent chunking in `ds.xds_to_zarr`. 

```python
>>> ds.to_zarr("blah.zarr", mode="w")
>>> zarr.open("blah.zarr").a.chunks
 (100, 16)

>>> zarr.open("blah.zarr").b.chunks
(20,)
```

Different chunking for the same dimension on different arrays? I can't see a use case and it would make aligning arrays along say the "row" dimension difficult when reading in the dataset. What do people think about this?

> Edit: Granted, the rechunk will do absolutely nothing if uvw is unused. #118 is actually slightly different.

Yes. Also, creating xarray datasets and dask arrays is cheap.

**Comment by landmanbester** [comment] 2021-11-25 12:14
> Different chunking for the same dimension on different arrays? I can't see a use case and it would make aligning arrays along say the "row" dimension difficult when reading in the dataset. What do people think about this?

Terrible idea for chunks on disk but I don't see any problem with it if the object just refers to an array that will be evaluated lazily. My problem is that I am chunking finely on disk, reading with a different chunking scheme and then trying to write out a variable with the same chunking I have on disk. Maybe there should be a way to distinguish between on disk vs in memory chunks and only complain if the chunks on disk are not aligned?

**Comment by sjperkins** [comment] 2021-12-07 09:37
xarray's `to_zarr` method has some magic behind the scenes to unify inconsistent chunking that has not been replicated in `xds_to_zarr`. A simple workaround is to create a new dataset with the columns you wish to write by selecting them out of the existing dataset as described here:

https://stackoverflow.com/a/47334689

**Comment by sjperkins** [comment] 2021-12-07 09:38
I'll leave this open in case we want dask-ms to automatically unify chunks prior to writing.

**Comment by JSKenyon** [comment] 2022-04-13 11:38
This is now partially fixed as a result of https://github.com/ratt-ru/dask-ms/pull/200. Schemas are no longer created for dataset components which are not going to be written to disk. The above example will now run through, but will fail if `columns=["weight", "uvw"]`. This is a sensible failure case (for now), as in this instance the chunking will be inconsistent.

**Comment by JSKenyon** [comment] 2022-04-14 13:05
Closing this - #200 in conjunction with #204 should be sufficient to circumvent these issues. Trying to write multiple columns/fields with inconsistent dims is still a failure case, but it should error out informatively.

**Closed by JSKenyon** 2022-04-14 13:05 UTC
Labels: enhancement
