### ISSUE TITLE
By default xds_to_table will create columns with standard (instead of tiled) storage managers

### ISSUE THREAD

**Issue by landmanbester** [ratt-ru/dask-ms#195] opened 2022-04-11 10:46 UTC
* dask-ms version: master branch
* Python version: 3.9
* Operating System: ubunu 2004

### Description

When writing a column that does not yet exist to a measurement set using xds_to_table it ends up having a standard storage manager associated with it. This can result in suboptimal performance when writing columns with channel and/or correlation axes. 
dask-ms should detect if this is the case and use a tiled storage manager instead.

**Comment by bennahugo** [comment] 2022-04-11 11:55
It may actually be advantageous to use an incremental storage manager for
cases where multiple fields may be written one at a time - EG default
initialization of MODEL_DATA which is only filled out by software later.

**Comment by JSKenyon** [comment] 2022-04-12 07:50
Closed via #196. Will leave it in master for you to test out @landmanbester. Reopen if you have trouble.

**Comment by JSKenyon** [comment] 2022-04-12 11:21
Weirdly, I cannot reproduce @landmanbester. If you change `TESTCOL to `DIFFTESTCOL`, do you get the same error?

**Comment by landmanbester** [comment] 2022-04-12 13:22
Same error. As discussed I also tried on an actual (as opposed to simulated) MeerKAT MS and I didn't get the same issue. The MS I was using originally was produced by makems so maybe something is going wrong there

**Comment by JSKenyon** [comment] 2022-04-12 13:30
The issue is the suffix on your MS. `dask-ms` where a column lives when building descriptors. Using `name.MS_p0` confuses the descriptor builder. If you are happy with the explanation (and the fix i.e. just don't change the suffix), go ahead and close again.

**Closed** 2022-04-12 13:33 UTC
